### ISSUE TITLE
Sass mixin

### ISSUE THREAD

**Issue by vuxor** [nenad-it-obuka/quantox-praksa#5]
https://github.com/nenad-it-obuka/quantox-praksa/blob/3ffb5e07ef66bff0d84010276c4f4acdff94be29/styles/input.scss#L44
You can group multiple rules that are font related and create a mixin that can be reused in your sass files.

**Comment by nenad-it-obuka** [comment]
Since I have changed sass files and their content I haven't found multiple rules that can be used as a mixin.
Instead of that I have created partial named _fonts.scss and imported it in main.scss file.
